### ISSUE TITLE
Small rectangle in top left corner of exported chart

### ISSUE THREAD

**Issue by ChiefDog** [imclem/Highcharts-export-module-asp.net#12]
I am planning on using the NET export module with Highcharts, however I get a small rectangle 
appearing in the top left corner of every chart that I export. This only appears on png, pdf and jpg files, not the svg. Has anyone encountered this issue?

**Comment by mrchief** [comment]
I'm facing this issue too. Apparently this happens for newer highcharts version (like 2.3). With v2.2.5, this doesn't happen.

**Comment by Tek4** [comment]
Most likely another bug with Svg.dll, but if it only recently appeared it
could be worth posting as an issue to Highcharts. Perhaps they can find a
workaround to avoid the Svg.dll bug.

**Comment by mrchief** [comment]
Yeah. Seems like that. 

The box is actually the tooltip. Although set to `visibility:hidden` it shows up. Even in Inkscape. Older versions highcharts (v2.2.5) were setting the height/width to zero but the latest one (v2.3) seems to set a height/width of 10 which is why it appears.

The workaround is to disable tooltip while exporting

`chart.exportChart({ url:'...'}, {tooltip: {enabled:false}});`

There are other issues though - such as elongated line on a pie chart for small values.

**Comment by Tek4** [comment]
Fine work! Thanks for sharing your workaround.

**Comment by ChiefDog** [comment]
Great. Thanks for the quick response!

**Comment by ghost** [comment]
The workaround is not working for me.  Can you tell me what is wrong with my code?

```
                       exporting: {
                            enabled: true,
                            buttons: {
                                exportButton: {
                                    onclick: function () {
                                        chart.exportChart(null, { tooltip: { enabled: false} });
                                    }
                                }
                            }
                        }
```

**Comment by drbombay14** [comment]
Disabling tooltips works perfectly, here's my settings:

``` javascript
exporting: {
    buttons: {
        exportButton: {
            onclick: function() {
                this.exportChart({
                    type: 'image/png'
                }, {
                    tooltip: {enabled: false}
                })
            }
        }
    }
}
```

**Comment by jdimov** [comment]
I have reported issue's description here:
http://highslide.com/forum/viewtopic.php?f=9&t=21294

There is white squire in top-left angle which is not visible on the chart. It's a hidden tooltip. 

Also I can see white borders in stackbar charts between stack pieces which are not displayed in component. The 'borderWidth' property in PlotOptions/Column is set to value 0.

Thank you
Yordan

**Comment by jdimov** [comment]
Is there any progress for this issue?

**Comment by Tek4** [comment]
Ensure that you have the latest copy of Highcharts. I am not aware of progress on this issue, yet the latest release addressed a very significant number of issues. Please report if it is solved.

http://www.highcharts.com/download

**Comment by Tek4** [comment]
Again, I want to re-iterate that rendering issues CANNOT be fixed by this project. This project does NO RENDERING and only supplies the "plumbing" for ASP.NET. It uses the "SVG Rendering Engine" below:

http://svg.codeplex.com/

It is unfortunate that the third-party SVG project seems to have little---if any---ongoing activity. Rendering errors would be best addressed by progress on that project. Short of that, work-arounds might be found via clever coding.

It is possible that the authors of Highcharts might incorporate a simple work-around into their product if it is clearly identified to them. However, I very much doubt they would expend much effort catering to anything beyond the extremely minor.

**Comment by Tek4** [comment]
UPDATE: There appears to be a fork of the SVG.dll project in active development here: https://github.com/vvvv/SVG --- let us know if you try it!

**Comment by imclem** [comment]
Please try with this version 76cf6a397e763d16774ffa8a72bb572f2b5f7bb9 and let us know if it fixes the problem.
